# config.yml
appname: "Travellers Palm"
mode: "development"
public_dir: "public"
root: "/usr/src/app"
secrets:
  - f22ebd363e5fffa6826f785b72de3c50db11aa67

databases:
  jadoo:
    dsn: "dbi:SQLite:dbname=/usr/src/app/db/Jadoo_2006.db"
    username: ""
    password: ""
    dbi_params:
      RaiseError: 1
      AutoCommit: 1
      PrintError: 1

  users:
    dsn: "dbi:SQLite:dbname=/usr/src/app/db/users.db"
    username: ""
    password: ""
    dbi_params:
      RaiseError: 1
      AutoCommit: 1
      PrintError: 1

plugins:
  - MemcachedFast:
      servers:
        - "127.0.0.1:11211"
      default_timeout: 3600

plack_middlewares:
  -
    - Expires
    - content_type
    -
      - image/gif
      - image/jpeg
      - image/png
      - text/css
      - application/javascript
    - expires
    - access plus 3 days
  -
    - Deflater