# config.yml
appname: "Travellers Palm"
mode: "development"
public_dir: "public"
root: "/usr/src/app"
secrets:
  - f22ebd363e5fffa6826f785b72de3c50db11aa67

log:
  level: debug
  path: /usr/src/app/log/app.log
  timezone: "Asia/Kolkata"

email:
  error:
    from:    'system@travellerspalm.com'
    subject: '500 Error Notification'

template_tokens:
  PHONE1: "+91 88051 22221"
  PHONE2: "+91 90111 55551"
  TAILOR: "tailor-made"
  THEMES: "themes"
  STATES: "states"
  REGIONS: "regions"
  IDEAS: "ideas"
  IMAGE: "http://images.travellers-palm.com"
  domain: "www.travellers-palm.com"
  
main_database: jadoo

databases:
  jadoo:
    dsn: "dbi:SQLite:dbname=/usr/src/app/localdb/Jadoo_2006.db"
    username: ""
    password: ""
    dbi_params:
      RaiseError: 1
      AutoCommit: 1
      PrintError: 1

  users:
    dsn: "dbi:SQLite:dbname=/usr/src/app/localdb/users.db"
    username: ""
    password: ""
    dbi_params:
      RaiseError: 1
      AutoCommit: 1
      PrintError: 1

memcached:
  servers:
    - "127.0.0.1:11211"
  default_timeout: 3600

plack_middlewares:
  -
    - Expires
    - content_type
    -
      - image/gif
      - image/jpeg
      - image/png
      - text/css
      - application/javascript
    - expires
    - access plus 3 days
  -
    - Deflater