requires 'Mojolicious';
requires 'Mojolicious::Plugin::TtRenderer';
requires 'Mojolicious::Plugin::YamlConfig';
# requires 'Mojolicious::Plugin::TemplateToolkit';
requires 'Template::Plugin::Comma';
requires 'DBI';
requires 'DBD::SQLite';
requires 'JSON';
requires 'DateTime';
requires 'File::Spec';
requires 'YAML::XS';
requires 'Data::FormValidator';
requires 'Data::Dumper';
