services:
  travellers_palm_app:
    build: .
    container_name: travellers_palm_app
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/local  # preserve installed modules
      - ./data:/usr/src/app/data  # Persistent DB & runtime data
      - ./log:/usr/src/app/log # Application logs
      - ./lib:/usr/src/app/lib:ro  # Mount code read-only
      - ./templates:/usr/src/app/templates:ro
      - ./public:/usr/src/app/public:ro
      - ./localdb:/usr/src/app/localdb:ro
    ports:
      - "3000:3000"
    restart: always

  nginx:
    image: nginx:alpine
    container_name: travellers_palm_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/usr/src/app/public:ro
    depends_on:
      - travellers_palm_app
