services:
  travellers_palm_app:
    build: .
    command: morbo -l http://*:3000 script/travellers_palm
    ports:
      - "3000:3000"
    container_name: travellers_palm_app
    volumes:
      - ./data:/usr/src/app/data       # <— host:container
    expose:
      - "3000"

  nginx:
    image: nginx:alpine
    container_name: travellers_palm_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/usr/src/app/public:ro
    depends_on:
      - travellers_palm_app
