version: "3.9"

services:
  travellers_palm_app:
    build: .
    container_name: travellers_palm_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./data:/usr/src/app/data            # Persistent DB & runtime data
      - ./log:/usr/src/app/log              # Logs
      - ./carton_cache:/usr/src/app/carton_cache  # Persist Carton modules & snapshot
    restart: always

  nginx:
    image: nginx:alpine
    container_name: travellers_palm_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/usr/src/app/public:ro
    depends_on:
      - travellers_palm_app
